AWSTemplateFormatVersion: '2010-09-09'
Description: 'Nested stack for creating AWS Lake Formation resources'

Parameters:
  DataLakeBucketName:
    Type: String
    Description: 'Name of the S3 bucket to use as the data lake'
  CodeBuildRole:
    Type: String
    Description: 'Code Build Role Which is used to build all CF reosurces'    
  GlueCrawlerRoleArn:
    Type: String
    Description: 'Code Build Role Which is used to build all CF reosurces'

Resources:
  LakeFormationDataLakeSettings:
    Type: AWS::LakeFormation::DataLakeSettings
    Properties:
      Admins: 
        - DataLakePrincipalIdentifier: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
        - DataLakePrincipalIdentifier: !Sub 'arn:aws:iam::${AWS::AccountId}:role/service-role/${CodeBuildRole}'
      CreateDatabaseDefaultPermissions: []  # Empty list to uncheck default settings
      CreateTableDefaultPermissions: []  # Empty list to uncheck default settings

#Registering DataLake Bucket in lakeFormation
  LakeFormationResource:
    Type: AWS::LakeFormation::Resource
    Properties:
      ResourceArn: !Sub 'arn:aws:s3:::${DataLakeBucketName}' #Registering DataLake Bucket in the account
      UseServiceLinkedRole: true

# Grant Data Location permissions to the crawler role
  DataLocationPermissions:
    Type: AWS::LakeFormation::PrincipalPermissions
    DependsOn: LakeFormationResource    
    Properties:
      Resource:
        DataLocation:
          CatalogId: !Ref AWS::AccountId  # Account ID where S3 bucket is registered
          S3Resource: !Sub 'arn:aws:s3:::${DataLakeBucketName}'
      Principal:
        DataLakePrincipalIdentifier: !Ref GlueCrawlerRoleArn
      Permissions:
        - DATA_LOCATION_ACCESS