AWSTemplateFormatVersion: '2010-09-09'
Description: 'Nested stack for creating AWS Lake Formation resources'

Parameters:
  DatabaseName:
    Type: String
    Description: 'Name of the Glue Database to store the crawled data'
  GlueCrawlerRoleArn:
    Type: String
    Description: 'Code Build Role Which is used to build all CF reosurces'

Resources:

# Grant LF permissions to the crawler role to modify/view DB
  DataLocationPermissions:
    Type: AWS::LakeFormation::PrincipalPermissions
    Properties:
      Resource:
        Database:
          CatalogId: !Ref AWS::AccountId  # Account ID where S3 bucket is registered
          Name: !Ref DatabaseName
      Principal:
        DataLakePrincipalIdentifier: !Ref GlueCrawlerRoleArn
      Permissions:
        - "CREATE_TABLE" 
        - "ALTER" 
        - "DROP"
        - "DESCRIBE"
      PermissionsWithGrantOption:
        - "DESCRIBE"