AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket

Parameters:
  EnvType:
    Type: String
    Default: "dev"
    Description: The environment type (e.g., prod, dev)
  DomainName:
    Type: String
    Description: The name of the domain

#IAMRole Parameters
  IAMRolePath:
    Type: String
    Description: IAM Role yaml path

#GlueDB Parameters
  GlueDBPath:
    Type: String
    Description: Database yaml path    

#Crawler Parameters   
  GlueCrawlerPath:
    Type: String
    Description: Crawler yaml path

#LF Parameters
  LFStackUrl:
    Type: String
    Description: 'LF Stack S3 URL of the nested stack template'
  DataLakeBucket:
    Type: String
    Description: Crawler yaml path
    Default: "landing-console-2"

Resources:
  IAMRoles:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref IAMRolePath
      Parameters:
        EnvType: !Ref EnvType
        DomainName: !Ref DomainName

  GlueDatabase:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref GlueDBPath
      Parameters:
        EnvType: !Ref EnvType
        DomainName: !Ref DomainName

  GlueCrawler:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAMRoles
    Properties:
      TemplateURL: !Ref GlueCrawlerPath
      Parameters:
        EnvType: !Ref EnvType
        DomainName: !Ref DomainName
        DatabaseName: !GetAtt GlueDatabase.Outputs.DatabaseName
        S3Target: !Ref DataLakeBucket
        GlueCrawlerRoleArn: !GetAtt IAMRoles.Outputs.GlueCrawlerRoleArn

  LakeFormationStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref LFStackUrl
      Parameters:
        DataLakeBucketName: !Ref DataLakeBucket
        DatabaseName: !GetAtt GlueDatabase.Outputs.DatabaseName

Outputs:
  DatabaseName:
    Description: 'Name of the Glue Database'
    Value:  !GetAtt GlueDatabase.Outputs.DatabaseName
  CrawlerName:
    Description: 'Name of the created Glue Crawler'
    Value:  !GetAtt GlueCrawler.Outputs.CrawlerName
  GlueCrawlerRoleArn:
    Description: 'Glue Crawler IAM Role'
    Value: !GetAtt IAMRoles.Outputs.GlueCrawlerRoleArn
    Export:
      Name: GlueCrawlerRoleArn
